{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 3}, "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture(autouse=True)\n    def write_stat():\n        if not checkout_positive(f'ls {data[\"local_path\"]}',\n                                 data[\"stat_file\"]):\n            checkout_positive(f'echo > \"{data[\"local_path\"]}/{data[\"stat_file\"]}\"; ls {data[\"local_path\"]}',\n                              data[\"stat_file\"])\n    \n>       with open(f'{data[\"local_path\"]}/{data[\"stat_file\"]}', 'a', encoding='utf-8') as f_stat:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'tst/stat.txt'\n\nconftest.py:83: FileNotFoundError\n", "test_name": "test_step1", "rerun": "0"}, "1": {"status": "ERROR", "message": "@pytest.fixture(autouse=True)\n    def write_stat():\n        if not checkout_positive(f'ls {data[\"local_path\"]}',\n                                 data[\"stat_file\"]):\n            checkout_positive(f'echo > \"{data[\"local_path\"]}/{data[\"stat_file\"]}\"; ls {data[\"local_path\"]}',\n                              data[\"stat_file\"])\n    \n>       with open(f'{data[\"local_path\"]}/{data[\"stat_file\"]}', 'a', encoding='utf-8') as f_stat:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'tst/stat.txt'\n\nconftest.py:83: FileNotFoundError\n", "test_name": "test_step2", "rerun": "0"}, "2": {"status": "ERROR", "message": "@pytest.fixture(autouse=True)\n    def write_stat():\n        if not checkout_positive(f'ls {data[\"local_path\"]}',\n                                 data[\"stat_file\"]):\n            checkout_positive(f'echo > \"{data[\"local_path\"]}/{data[\"stat_file\"]}\"; ls {data[\"local_path\"]}',\n                              data[\"stat_file\"])\n    \n>       with open(f'{data[\"local_path\"]}/{data[\"stat_file\"]}', 'a', encoding='utf-8') as f_stat:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'tst/stat.txt'\n\nconftest.py:83: FileNotFoundError\n", "test_name": "test_step3", "rerun": "0"}}, "suite_name": "test_7z_negative.py"}}}, "date": "August 19, 2023", "start_time": 1692448531.9518213, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "3", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}